compile:
  script:
    - source ci/setup_ws.sh
    - catkin_make

  tags:
    - sim0

test:
  script:
    - source ci/setup_ws.sh
    - catkin_make
    - catkin_make run_tests
    - catkin_test_results

  tags:
    - sim0
  except:
    - sloigge/diagnosis
    - sloigge/observers
    - sloigge/resource_monitor
    - cmuehlbacher/rule_system