compile_with_test:
  script:
    - source ci/setup_ws.sh
    - source ci/clone_required_repos.sh
    - catkin_make
    - catkin_make run_tests 

  tags:
    - sim0
  except:
    - master
    - safdar
