rules:
  - type: service
    service_name: '/test_service'
    service_type: 'tug_reporter/SetString'
    call_msg: "message: 'test'"
    positive_possible_faulty_resources:
        - resource: 'imu'
