rules:
  - type: process
    process: "rosrun tug_reporter test.sh"
    positive_observations:
        - type: 'hz'
          resource: 'imu'
          observation: 0
    recall_duration: 10.0
  - type: print
    message: 'second rule'
    positive_possible_faulty_resources:
        - resource: 'imu'
    recall_duration: 10.0
