"""autogenerated by genpy from tug_ist_diagnosis_msgs/Channel.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Channel(genpy.Message):
  _md5sum = "a892da4b04bb1ee7a9c52668e370ec76"
  _type = "tug_ist_diagnosis_msgs/Channel"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 id
string dev_connected
int32 status
float32 current
float32 voltage

"""
  __slots__ = ['id','dev_connected','status','current','voltage']
  _slot_types = ['int32','string','int32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,dev_connected,status,current,voltage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Channel, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.dev_connected is None:
        self.dev_connected = ''
      if self.status is None:
        self.status = 0
      if self.current is None:
        self.current = 0.
      if self.voltage is None:
        self.voltage = 0.
    else:
      self.id = 0
      self.dev_connected = ''
      self.status = 0
      self.current = 0.
      self.voltage = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_i.pack(self.id))
      _x = self.dev_connected
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_i2f.pack(_x.status, _x.current, _x.voltage))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (self.id,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dev_connected = str[start:end].decode('utf-8')
      else:
        self.dev_connected = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.status, _x.current, _x.voltage,) = _struct_i2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_i.pack(self.id))
      _x = self.dev_connected
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_i2f.pack(_x.status, _x.current, _x.voltage))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.id,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dev_connected = str[start:end].decode('utf-8')
      else:
        self.dev_connected = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.status, _x.current, _x.voltage,) = _struct_i2f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_i2f = struct.Struct("<i2f")
