  nodes:
#    - name: "imu"
#      sub_topic: []
#      pub_topic: ["/imu_topic"]

    - name: "timing_node"
      sub_topic: []
      pub_topic: ["/topicA", "/topicB"]

#    - name: "loam"
#      sub_topic: []
#      pub_topic: ["/loam_topic"]

#    - name: "base"
#      sub_topic: []
#      pub_topic: ["/odom_topic", "/cmd_topic"]

  observations:
  #  - type: "resource"
  #    nodes: ["imu", "loam", "base"]
#    - type: "hz"
#      topics: ["/imu_topic", "/loam_topic", "/odom_topic", "/cmd_topic"]

  #  - type: "timestamp"
  #    topics: ["/imu_topic", "/loam_topic", "/odom_topic", "/cmd_topic"]

  #  - type: "timeout"
  #    topics: ["/imu_topic", "/loam_topic", "/odom_topic", "/cmd_topic"]
  #
    - type: "timing"
      topics: [["/topicA", "/topicB"]]
#    - type: "movement"
#      topics: [["/imu_topic", "/loam_topic"],
#               ["/imu_topic", "/odom_topic"],
#               ["/imu_topic", "/cmd_topic"],
#               ["/loam_topic", "/odom_topic"],
#               ["/loam_topic", "/cmd_topic"],
#               ["/odom_topic", "/cmd_topic"]]
