########## node1 ##########
setup:
- type: hz
  topics:
  - name: /topicA
    filter:
      type: lp
      # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
      decay_rate: 1.0
    states:
    - state: '1'
      frequenzy:
        type: gaus
        mean: 1.0
        std_deviation: 1.0
    - state: '2'
      frequenzy:
        type: gaus
        mean: 5.0
        std_deviation: 1.0

- type: size
  topics:
  - name: /topicA
    states:
    - state: 1
      bytes:
        type: gaus
        mean: 10000
        std_deviation: 100

- type: timings
  topics:
  - nameA: /topicA
    nameB: /topicB
    states:
    - state: 1
      delay:
        type: gaus
        mean: 10.0           # delay in ms from A to B
        std_deviation: 1.0   # std_deviation in ms
      sampling_rate:
        type: gaus
        mean: 10.0           # sampling rate from A to B
        std_deviation: 0.1

