########## node1 ##########
setup:
- type: hz
  topics:
  - name: /topicA
    callerids:
    - callerid: unknown
      timeout: 1.0
      filter:
        type: nofilter
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
        decay_rate: 0.05
      states:
      - state: 'gaus'
        frequenzy:
          type: gaus
          mean: 10.0
          std_deviation: 1.0
      - state: 'exact'
        frequenzy:
          type: exact
          exact: 5 
      - state: 'not'
        frequenzy:
          type: not
          exact_not: 5 
      - state: 'greater_than'
        frequenzy:
          type: greather_than
          greater_than: 5.0 
      - state: 'less_than'
        frequenzy:
          type: less_than
          less_than: 5.0 
      - state: 'in_between'
        frequenzy:
          type: in_between
          lower_bound: 5.0
          upper_bound: 15.0
  - name: /topicB
    callerids:
    - callerid: unknown
      timeout: 1.0
      filter:
        type: nofilter
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
        decay_rate: 0.05
      states:
      - state: 'gaus'
        frequenzy:
          type: gaus
          mean: 10.0
          std_deviation: 1.0
      - state: 'exact'
        frequenzy:
          type: exact
          exact: 5 
      - state: 'not'
        frequenzy:
          type: not
          exact_not: 5 
      - state: 'greater_than'
        frequenzy:
          type: greather_than
          greater_than: 5.0 
      - state: 'less_than'
        frequenzy:
          type: less_than
          less_than: 5.0 
      - state: 'in_between'
        frequenzy:
          type: in_between
          lower_bound: 5.0
          upper_bound: 15.0 
  - name: /topicC
    callerids:
    - callerid: unknown
      timeout: 1.0
      filter:
        type: nofilter
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
        decay_rate: 0.05
      states:
      - state: 'gaus'
        frequenzy:
          type: gaus
          mean: 10.0
          std_deviation: 1.0
      - state: 'exact'
        frequenzy:
          type: exact
          exact: 5 
      - state: 'not'
        frequenzy:
          type: not
          exact_not: 5 
      - state: 'greater_than'
        frequenzy:
          type: greather_than
          greater_than: 5.0 
      - state: 'less_than'
        frequenzy:
          type: less_than
          less_than: 5.0 
      - state: 'in_between'
        frequenzy:
          type: in_between
          lower_bound: 5.0
          upper_bound: 15.0 
  - name: /topicD
    callerids:
    - callerid: unknown
      timeout: 1.0
      filter:
        type: nofilter
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
        decay_rate: 0.05
      states:
      - state: 'gaus'
        frequenzy:
          type: gaus
          mean: 10.0
          std_deviation: 1.0
      - state: 'exact'
        frequenzy:
          type: exact
          exact: 5 
      - state: 'not'
        frequenzy:
          type: not
          exact_not: 5 
      - state: 'greater_than'
        frequenzy:
          type: greather_than
          greater_than: 5.0 
      - state: 'less_than'
        frequenzy:
          type: less_than
          less_than: 5.0 
      - state: 'in_between'
        frequenzy:
          type: in_between
          lower_bound: 5.0
          upper_bound: 15.0 
  - name: /topicE
    callerids:
    - callerid: unknown
      timeout: 1.0
      filter:
        type: nofilter
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
        decay_rate: 0.05
      states:
      - state: 'gaus'
        frequenzy:
          type: gaus
          mean: 10.0
          std_deviation: 1.0
      - state: 'exact'
        frequenzy:
          type: exact
          exact: 5 
      - state: 'not'
        frequenzy:
          type: not
          exact_not: 5 
      - state: 'greater_than'
        frequenzy:
          type: greather_than
          greater_than: 5.0 
      - state: 'less_than'
        frequenzy:
          type: less_than
          less_than: 5.0 
      - state: 'in_between'
        frequenzy:
          type: in_between
          lower_bound: 5.0
          upper_bound: 15.0 



- type: size
  topics:
  - name: /topicA
    states:
    - state: 1
      bytes:
        type: gaus
        mean: 10000
        std_deviation: 100

- type: timings
  topics:
  - nameA: /topicA
    nameB: /topicB
    states:
    - state: 1
      delay:
        type: gaus
        mean: 10.0           # delay in ms from A to B
        std_deviation: 1.0   # std_deviation in ms
      sampling_rate:
        type: gaus
        mean: 10.0           # sampling rate from A to B
        std_deviation: 0.1

