########## node1 ##########
setup:
- type: hz
  topics:
  - name: /topicA
    callerids:
    - callerid: []
      timeout: 1.0
      filter:
        type: ewma                      #exponentially weighted moving average
        window_size: 200
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
        decay_rate: 0.05
        deviation_type: std_deviation   # std_deviation, min_max
      states:
      - state: 'gauss'
        frequenzy:
          type: nominal_value
          value:
            type: gauss
            mean: 1.0
            std_deviation: 1.0
          deviation:
          - type: in_between
            lower_bound: 0.0
            upper_bound: 0.01
        #  - type: in_between
        #    lower_bound: 5.0
        #    upper_bound: 15.0
        
          type: student_t
          true_mean: 10.0
          significance_level: 0.9

          type: f_test
          significance_level: 0.9

- type: size
  topics:
  - name: /topicA
    states:
    - state: 1
      bytes:
        type: gaus
        mean: 10000
        std_deviation: 100

- type: timings
  topics:
  - nameA: /topicA
    nameB: /topicB
    states:
    - state: 1
      delay:
        type: gaus
        mean: 10.0           # delay in ms from A to B
        std_deviation: 1.0   # std_deviation in ms
      sampling_rate:
        type: gaus
        mean: 10.0           # sampling rate from A to B
        std_deviation: 0.1

