########## node1 ##########
setup:
- type: hz
  main_loop_rate: 1.0
  topics:
  - name: /topicA
    callerids:
    - callerid: []
      filter:
        type: ewma                      #exponentially weighted moving average
        window_size: 200
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
        decay_rate: 0.05
        k_size: 10
        deviation_type: std_deviation   # std_deviation, min_max
      states:
      - state: 'gauss'
        frequenzy:
          #type: nominal_value
          #value:
          #  type: gauss
          #  mean: 0.1
          #  std_deviation: 0.25
          #deviation:
          #- type: in_between
          #  lower_bound: 0.0
          #  upper_bound: 0.01
        #  - type: in_between
        #    lower_bound: 5.0
        #    upper_bound: 15.0

          type: student_t
          true_mean: 0.10
          significance_level: 0.05

        #  type: f_test
        #  significance_level: 0.9

