- type: resources
  nodes:
  - name: /node
    states:
    - state: 1
      cpu_usage: 100
      cpu_usage_std_deviation: 15
      cpu_filter:
        filter_name: mean
        window_size: 10
      # mem usage in bytes
      mem_usage: 1024
      # mem usage std deviation in bytes
      mem_usage_std_deviation: 100
      mem_filter:
        filter_name: mean
        window_size: 10